#! /bin/sh
# agb
# Copyright (C) 2015 giulio <giulioungaretti@me.com>
#
# Distributed under terms of the MIT license.
#
export OLDPS1=$PS1
export OLDGOpath=$GOPATH
GB_PROJECT_DIR=$(gb env)
string="$GB_PROJECT_DIR"
substring="FATAL"
if test "${string#*$substring}" != "$string"
then
        echo "Not in a gb project"
        return 1    # $substring is not in $string
else
        GB_PROJECT_DIR=$(echo $GB_PROJECT_DIR | sed s/\"//g )
        GB_PROJECT_DIR=$(echo $GB_PROJECT_DIR | sed s/GB_PROJECT_DIR\=//g )
        GB_PROJECT_DIR=$(echo $GB_PROJECT_DIR | head -n 1)
        export GB_PROJECT_DIR=$GB_PROJECT_DIR
        export GOPATH=$GOPATH:$GB_PROJECT_DIR:$GB_PROJECT_DIR/vendor
        PROJECT=$(basename $GB_PROJECT_DIR)
        export PS1='%F{white}(gb:$PROJECT)'$PS1
        export src=$GB_PROJECT_DIR"/src/"$PROJECT
        return 0    # $substring is in $string
fi
